-- Catálogo: SIN seed. Los productos vienen de la sincronización real con Contabilium (ERP),
-- no de datos inventados (decisión 2026-07-28 — más fiel a la regla de oro que un seed ficticio).
-- El catálogo arranca VACÍO; se puebla con `POST /admin/contabilium/sync-productos` (botón
-- "Sincronizar catálogo" del panel /integraciones, requiere CONTABILIUM_MODE=live).
--
-- Nota: `DevDataSeeder` (perfil dev) ya contempla el catálogo vacío — crea el nutricionista demo
-- + pacientes y SALTEA las recetas demo si no hay productos (guard `productos.isEmpty()`).
--
-- Se deja este archivo como no-op para preservar la secuencia de versiones Flyway (V001..V004).
-- El seed anterior (12 suplementos ficticios) se removió en esta versión.
